import fs from "fs-extra";
import path from "node:path";

function getFallbackContent(filename) {
  if (filename.endsWith(".yaml")) return "# autogenerated\n";
  if (filename.endsWith(".xml")) return "<!-- autogenerated -->\n";
  if (filename.endsWith(".json")) return "{}\n";
  if (filename.endsWith(".sh")) return "#!/bin/bash\n";
  return "";
}

/**
 * mode:
 *  - 'standard' → copy defaults if available
 *  - 'blank'    → never copy defaults, always fallback
 *
 * NOTE: template source values look like "defaults/points.yaml"
 * but baseDir already points to pm_defaults, so we strip the
 * leading "defaults/" segment before resolving the srcPath.
 */
async function generateFromTemplate(
  template,
  projectPath,
  baseDir,
  mode = "standard"
) {
  // Create directories
  for (const dir of template.directories) {
    await fs.ensureDir(path.join(projectPath, dir));
  }

  // Create files
  for (const [scope, files] of Object.entries(template.files)) {
    const targetDir =
      scope === "root"
        ? projectPath
        : path.join(projectPath, scope);

    await fs.ensureDir(targetDir);

    for (const [filename, source] of Object.entries(files)) {
      const dstPath = path.join(targetDir, filename);

      if (await fs.pathExists(dstPath)) continue;

      // Normalize "defaults/" prefix
      const normalizedSource = source.replace(/^defaults\//, "");
      const srcPath = path.join(baseDir, normalizedSource);

      const shouldCopyDefaults =
        mode === "standard" && (await fs.pathExists(srcPath));

      if (shouldCopyDefaults) {
        await fs.copy(srcPath, dstPath);
      } else {
        if (mode === "standard") {
          console.warn(
            `[generateFromTemplate] Default not found: ${srcPath} — using fallback`
          );
        }

        const fallback = getFallbackContent(filename);
        await fs.writeFile(dstPath, fallback, "utf8");
      }

      if (filename.endsWith(".sh")) {
        await fs.chmod(dstPath, 0o755);
      }
    }
  }
}

export { generateFromTemplate };